language: csharp
solution: Fanray.sln
sudo: required
dist: xenial
dotnet: 3.1.101
mono: none
os:
  - linux

notifications:
  email:
    on_success: change
    on_failure: always

before_script:
  - dotnet restore

script:
  - dotnet build ./Fanray.sln
  - dotnet test --verbosity d ./test/Fan.Tests/Fan.Tests.csproj
