variables:
  buildConfiguration: 'Release'

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'  
  
  steps:
  - task: DotNetCoreInstaller@0
    displayName: 'Use .NET Core sdk 3.1.101'
    inputs:
      version: 3.1.101

  - script: |
      dotnet build --configuration $(buildConfiguration)
      dotnet test --no-build --verbosity d

- job: macOS
  pool:
    vmImage: 'macOS-latest'

  steps:
  - task: DotNetCoreInstaller@0
    displayName: 'Use .NET Core sdk 3.1.101'
    inputs:
      version: 3.1.101

  - script: |
      dotnet build --configuration $(buildConfiguration)
      dotnet test --configuration $(buildConfiguration)

- job: Windows
  pool:
    vmImage: 'windows-latest'
  
  steps:
  - task: DotNetCoreInstaller@0
    displayName: 'Use .NET Core sdk 3.1.101'
    inputs:
      version: 3.1.101

  - script: |
      dotnet build --configuration $(buildConfiguration)
      dotnet test --no-build --configuration $(buildConfiguration)

